#! /usr/bin/env python

import sys
import matplotlib.pyplot as pyplot
import numpy

#for filename in sys.argv[1:]:
#   with open(filename,'rt') as sf:

#TODO plot measurement locations from the input data file (or autogenerated locations in the program?)

# plots geolocation ellipses
#TODO add rotation based on eigenvector (function wasn't producing correct vectors...)
with open("georesults.csv",'rt') as sf:
      pyplot.ylim(ymax=20, ymin=-20)
      pyplot.xlim(xmax=20, xmin=-20)
      table = []
      for line in sf: table.append( [val for val in line.split(",")] )
      table = [ row for row in table if len(row) ] ## remove empty rows
      theta = numpy.linspace(0,2*numpy.pi)
      for row in table:
          ellipse = [float(row[2]) * numpy.cos(theta), float(row[3]) * numpy.sin(theta)]
          pyplot.plot((ellipse[0]+float(row[0]))/1852, (ellipse[1]+float(row[1]))/1852)

pyplot.show()

#TODO live plotting?
